begin;
select plan(17);

select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid = 'public.bank_checks'::regclass), 'bank checks force row-level security');
select ok(exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'bank_checks' and policyname = 'bank_checks_manager_read' and cmd = 'SELECT'), 'bank check reads require manager, admin, or supervisor membership');
select ok(not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'bank_checks' and cmd in ('INSERT','UPDATE','DELETE','ALL')), 'bank check writes cannot bypass RPC validation');
select ok(has_table_privilege('authenticated','public.bank_checks','SELECT') and not has_table_privilege('authenticated','public.bank_checks','INSERT') and not has_table_privilege('authenticated','public.bank_checks','UPDATE') and not has_table_privilege('authenticated','public.bank_checks','DELETE'), 'authenticated bank-check table access is read-only');
select ok(has_function_privilege('authenticated','public.save_bank_check(uuid,uuid,integer,jsonb)','EXECUTE'), 'authorized users can save bank checks through RPC');
select ok(not has_function_privilege('anon','public.save_bank_check(uuid,uuid,integer,jsonb)','EXECUTE'), 'anonymous users cannot save bank checks');
select ok(has_function_privilege('authenticated','public.delete_bank_check(uuid,uuid,integer)','EXECUTE'), 'authorized users can delete bank checks through RPC');
select ok(exists (select 1 from pg_trigger where tgrelid = 'public.bank_checks'::regclass and tgname = 'bank_checks_emit_event' and not tgisinternal), 'bank check writes emit shop-scoped Realtime events');

select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid = 'public.deferred_check_records'::regclass), 'deferred check records force row-level security');
select ok(exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'deferred_check_records' and policyname = 'deferred_checks_manager_read' and cmd = 'SELECT'), 'deferred check reads require manager, admin, or supervisor membership');
select ok(not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'deferred_check_records' and cmd in ('INSERT','UPDATE','DELETE','ALL')), 'deferred check writes cannot bypass RPC validation');
select ok(has_table_privilege('authenticated','public.deferred_check_records','SELECT') and not has_table_privilege('authenticated','public.deferred_check_records','INSERT') and not has_table_privilege('authenticated','public.deferred_check_records','UPDATE') and not has_table_privilege('authenticated','public.deferred_check_records','DELETE'), 'authenticated deferred-check access is read-only');
select ok(has_function_privilege('authenticated','public.create_deferred_check_record(uuid,jsonb)','EXECUTE'), 'authorized users can create deferred check records through RPC');
select ok(not has_function_privilege('anon','public.create_deferred_check_record(uuid,jsonb)','EXECUTE'), 'anonymous users cannot create deferred check records');
select ok(has_function_privilege('authenticated','public.delete_deferred_check_record(uuid,uuid)','EXECUTE'), 'authorized users can delete deferred check records through RPC');
select ok(exists (select 1 from pg_attribute where attrelid = 'public.deferred_check_records'::regclass and attname = 'remaining_amount' and attgenerated = 's'), 'remaining amount is generated by PostgreSQL, not trusted from the browser');
select ok(exists (select 1 from pg_trigger where tgrelid = 'public.deferred_check_records'::regclass and tgname = 'deferred_checks_emit_event' and not tgisinternal), 'deferred check writes emit shop-scoped Realtime events');

select * from finish();
rollback;
