import { collectProductBarcodes, getBarcodeFieldError } from "./productBarcodeSlots";

export type BarcodePrintLabel = { productName: string; barcode: string };

export const createBarcodePrintLabels = (productName: string, primary: string, additional: readonly string[]) => {
  const error = getBarcodeFieldError(primary, additional);
  if (error) return { labels: [] as BarcodePrintLabel[], error };
  const labels = collectProductBarcodes(primary, additional).map(barcode => ({
    productName: productName.trim() || "منتج",
    barcode,
  }));
  return { labels, error: null };
};

const escapeHtml = (value: string) => value
  .replace(/&/g, "&amp;")
  .replace(/</g, "&lt;")
  .replace(/>/g, "&gt;")
  .replace(/\"/g, "&quot;")
  .replace(/'/g, "&#39;");

/** Build a standalone A4 print sheet; each SVG must be generated by JsBarcode for its label value. */
export const createBarcodeLabelPrintHtml = (labels: BarcodePrintLabel[], barcodeSvgs: string[]) => {
  if (labels.length !== barcodeSvgs.length) throw new Error("Barcode label and SVG counts must match");
  const labelMarkup = labels.map((label, index) => `
    <article class="barcode-label">
      <h2>${escapeHtml(label.productName)}</h2>
      <div class="barcode-image">${barcodeSvgs[index]}</div>
      <p class="barcode-value" dir="ltr">${escapeHtml(label.barcode)}</p>
    </article>`).join("");

  return `<!doctype html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>ملصقات الباركود</title>
<style>
  * { box-sizing: border-box; }
  body { margin: 0; padding: 8mm; color: #111827; font-family: Arial, Tahoma, sans-serif; }
  .print-heading { margin: 0 0 5mm; text-align: center; font-size: 14pt; }
  .label-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 3mm; }
  .barcode-label { height: 29mm; padding: 2mm; border: 0.25mm dashed #94a3b8; display: flex; flex-direction: column; align-items: center; justify-content: space-between; overflow: hidden; break-inside: avoid; }
  .barcode-label h2 { width: 100%; margin: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; text-align: center; font-size: 9pt; font-weight: 700; }
  .barcode-image { width: 100%; height: 15mm; display: flex; align-items: center; justify-content: center; }
  .barcode-image svg { display: block; width: 100%; max-width: 52mm; height: 15mm; }
  .barcode-value { margin: 0; font-family: monospace; font-size: 9pt; letter-spacing: 0.5px; }
  @page { size: A4; margin: 7mm; }
  @media print { body { padding: 0; } .print-heading { display: none; } .barcode-label { border-color: #cbd5e1; } }
</style>
</head>
<body>
<h1 class="print-heading">ملصقات باركود المنتج</h1>
<main class="label-grid">${labelMarkup}
</main>
</body>
</html>`;
};
